### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by leeseetja** [kleok/FLOMPY#2]
FLOMPY runs well untill it gets to STEP 4 (i.e.  'Statistical_analysis'). I get the following error, which seems to do with converting NaN values to integers from line 109 (i.e. utm_zone = int(np.floor((representative_longitude + 180) / 6) + 1)) of the file Generate_aux.py. Please see the error below, and the attached image of the config file.

```
******************** step - Statistical_analysis ********************
/home/lesetl/anaconda3/envs/flompy/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
return _methods._mean(a, axis=axis, dtype=dtype,
/home/lesetl/anaconda3/envs/flompy/lib/python3.10/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
File "/home/lesetl/testbed/FLOMPY/flompy/FLOMPYapp.py", line 386, in <module>
main()
File "/home/lesetl/testbed/FLOMPY/flompy/FLOMPYapp.py", line 377, in main
app.run(steps=inps.runSteps, plot=inps.plot)
File "/home/lesetl/testbed/FLOMPY/flompy/FLOMPYapp.py", line 348, in run
self.run_multitemporal_statistics(sname)
File "/home/lesetl/testbed/FLOMPY/flompy/FLOMPYapp.py", line 311, in run_multitemporal_statistics
get_S1_aux (self.Preprocessing_dir)
File "/home/lesetl/testbed/FLOMPY/flompy/Generate_aux.py", line 146, in get_S1_aux
UTM_CRS_EPSG = WGS84_to_UTM(lon_list, lat_list)
File "/home/lesetl/testbed/FLOMPY/flompy/Generate_aux.py", line 109, in WGS84_to_UTM
utm_zone = int(np.floor((representative_longitude + 180) / 6) + 1)
ValueError: cannot convert float NaN to integer
(flompy) -bash-4.2$ python FLOMPYapp.py FLOMPYapp_template.cfg
FLOod Mapping PYthon toolbox (FLOMPY) v.1.0
Copyright (c) 2021-2022 Kleanthis Karamvasis, karamvasis_k@hotmail.com
Remote Sensing Laboratory of National Technical University of Athens
```

![conf_file](https://user-images.githubusercontent.com/57126813/173585232-2af8a3c0-b76a-44cf-975e-9884daee4af7.jpeg)

**Comment by kleok** [comment]
Hello @leeseetja,
The particular error is related to the big area [200x200km] that your AOI covers. In order to cover all this area you need to mosaic 3 GRD images for each Sentinel-1 pass. At the time of your experiment, FLOMPY was able to produce results only if the AOI was covered by a single Sentinel-1 GRD product. Based on your issue, I added a new functionality and now FLOMPY can mosaic 2 GRD Sentinel-1 images. I suggest you to try again with a smaller AOI. I performed an experiment over an smaller area close to your AOI and FLOMPY generated results successfully. Let me know if my updates works for you too :smile:

**Comment by kleok** [comment]
I would also like to point out that I implemented a plotting functionality which can help you understand if your flood event is visible at Sentinel-1 image. I suggest to have a look at the plots for each Sentinel-1 image (located at projectfolder) to find out if you have a considerable decrease of backscatter in the flood image with respect to the baseline images. If you are able to identify a decrease of backscatter in the flood image (darker tones in some areas), then you can expect that FLOMPY will generate a floodwater map. In cases that you have similar or bigger backscatter values of flood image with respect to baseline image due to complex backscatter mechanisms, FLOMPY`s results cannot be trusted.

**Comment by leeseetja** [comment]
Hi. I tried all your suggestions, and the issue was resolved. Thanks so much. You can consider this issue closed.
