### ISSUE TITLE
assert (os.path.exists(Flood_image))  AssertionError

### ISSUE THREAD

**Issue by mechtach714** [kleok/FLOMPY#3]
Good day Kleanthis,

You have been of invaluable assistance to myself and my colleague Nicolene Botha. After your last update we were able to obtain the flood map image for 5 February 2022. We are still going to look at the relOrbit variable as you suggested.

However, with the changes you made I can no longer get the flood map image for 9 December 2019, which I was able to get prior to the latest update. This is also the case for several other dates. It gives an assertion error and it appears that the file indicated in the flood_S1_filename.csv as the main image is not downloaded, hence the error.

I attach the error message, map.geojson and configuration file. In the configuration file you will see all the other dates of interest that are all giving the same assertion error. 
[FLOMPYapp.zip](https://github.com/kleok/FLOMPY/files/8926127/FLOMPYapp.zip)

Thanks again for your prompt assistance with every issue we have encountered. It is great when a developer is still actively maintaining their code. 

Kind regards
Natasha

**Comment by kleok** [comment]
Hello @mechtach714,
Based on the AssertionError, it seems that the flood image is not downloaded. I suggest you to follow the steps:
 - Delete all the files and directories in the projectfolder except [configuration file, geojson and folder Sentinel_1_GRD_imagery]
 - Pull/download the updated code. The configuration file structure is modified, so please make sure to update it and overwrite your old configuration parameter.
 - Rerun the FLOMPYapp.py 
You can find the configuration file that FLOMPY generated results successfully.
[FLOMPYapp_issue3.txt](https://github.com/kleok/FLOMPY/files/8950419/FLOMPYapp_issue3.txt)
Please let me know if this works for you too :smile:

**Comment by kleok** [comment]
Based on the following search (based on your configuration parameters), it seems that there is no image at 9 December 2019. [ASF data search](https://search.asf.alaska.edu/#/?polygon=POLYGON((27.8899%20-25.9453,28.2621%20-25.9453,28.2621%20-25.7748,27.8899%20-25.7748,27.8899%20-25.9453))&zoom=7.670&center=29.059,-27.180&start=2019-11-29T22:00:00Z&end=2019-12-12T21:59:59Z&productTypes=GRD_HD&resultsLoaded=true&granule=S1A_IW_GRDH_1SDV_20191210T164710_20191210T164735_030288_0376C0_C22F-GRD_HD) 
Please, let me know if this particular image (9/12/2019) is related to other configuration parameters.

**Comment by kleok** [comment]
I would also like to point out that I implemented a plotting functionality which can help you understand if your flood event is visible at Sentinel-1 image. I suggest to have a look at the plots for each Sentinel-1 image (located at projectfolder) to find out if you have a considerable decrease of backscatter in the flood image with respect to the baseline images. If you are able to identify a decrease of backscatter in the flood image (darker tones in some areas), then you can expect that FLOMPY will generate a floodwater map. In cases that you have similar or bigger backscatter values of flood image with respect to baseline image due to complex backscatter mechanisms, FLOMPY`s results cannot be trusted. I hope this helps you and saves you some time :smile:
