### ISSUE TITLE
ValueError: '20220128T164719' is not in list

### ISSUE THREAD

**Issue by mechtach714** [kleok/FLOMPY#4]
Good day,

I tried changing the relOrbit value to 50 and 116 as you suggested to my colleague in issue #1. Both resulted in a ValueError for the date, albeit different times. For relOrbit = 50 this error was "20211213T033455" and for relOrbit = 116 it was "20220128T164719".
![Screenshot from 2022-06-20 19-54-10](https://user-images.githubusercontent.com/103054856/174656486-dc802795-acaa-44bc-aef9-0d02606d93b3.png)

Thanks in advance!
Natasha

**Comment by kleok** [comment]
Hello @mechtach714,
I think this particular error is caused by re-running FLOMPYapp.py with different configuration but at the same **projectfolder**. Please make sure to change **projectfolder** at each run. In the future, a "re-run" functionality will be implemented in order to avoid this particular error. Let me know if you still encounter this error, after changing **projectfolder** parameter.
Happy to help :smile:

**Comment by mechtach714** [comment]
Hi @kleok, 

I've implemented all your suggestions and also updated to the latest version of the code. 

Unfortunately, I've been struggling since last week just downloading the ERA5 data, it seems they changed their infrastructure which has now increased download times. 

I'll let you know once FLOMPY runs through whether my issues are resolved. 

Thanks again!
Natasha
